moods = ['ecstatic',
                    'delighted',
                    'excited',
                    'energetic',
                    'happy',
                    'optimistic',
                    'hopeful',
                    'motivated',
                    'inspired',
                    'content',
                    'cheerful',
                    'playful',
                    'amused',
                    'proud',
                    'loving',
                    'grateful',
                    'satisfied',
                    'calm',
                    'relaxed',
                    'peaceful',
                    'curious',
                    'interested',
                    'nostalgic',
                    'bittersweet',
                    'zestful',
                    'lively',
                    'fidgety',
                    'inquisitive',
                    'surprised',
                    'confident',
                    'sympathetic',
                    'bored',
                    'indifferent',
                    'silly',
                    'confused',
                    'yearning',
                    'pensive',
                    'determined',
                    'motivated',
                    'tired',
                    'sleepy',
                    'satisfied',
                    'relaxed',
                    'content',
                    'indifferent',
                    'lonely',
                    'insecure',
                    'anxious',
                    'nervous',
                    'worried',
                    'helpless',
                    'vulnerable',
                    'uneasy',
                    'withdrawn',
                    'stressed',
                    'overwhelmed',
                    'frustrated',
                    'fearful',
                    'terrified',
                    'despondent',
                    'disheartened',
                    'disappointed',
                    'sad',
                    'depressed',
                    'hurt',
                    'lonely',
                    'rejected',
                    'ashamed',
                    'guilty',
                    'embarrassed',
                    'humiliated',
                    'angry',
                    'irritated',
                    'annoyed',
                    'frustrated',
                    'disgusted',
                    'resentful',
                    'jealous',
                    'cynical',
                    'pessimistic',
                    'bitter',
                    'resentful',
                    'disappointed',
                    'doubtful',
                    'insecure',
                    'helpless',
                    'hopeless'
                ]


import random

class Mood:
    def __init__(self):
        self.mood_level = 0
        self.current_mood = random.choice(moods)
        
        
    def __repr__(self):
        string = ''
        for attribute_name, attribute_value in vars(self).items():
            string += (f"{attribute_name}: {attribute_value}\n")
        return string[0:-1]
            